// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package internal

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTestdata returns the embedded CollectionSpec for testdata.
func loadTestdata() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TestdataBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load testdata: %w", err)
	}

	return spec, err
}

// loadTestdataObjects loads testdata and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*testdataObjects
//	*testdataPrograms
//	*testdataMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTestdataObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTestdata()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// testdataSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataSpecs struct {
	testdataProgramSpecs
	testdataMapSpecs
	testdataVariableSpecs
}

// testdataProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataProgramSpecs struct {
	Test *ebpf.ProgramSpec `ebpf:"test"`
}

// testdataMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataMapSpecs struct {
}

// testdataVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataVariableSpecs struct {
}

// testdataObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataObjects struct {
	testdataPrograms
	testdataMaps
	testdataVariables
}

func (o *testdataObjects) Close() error {
	return _TestdataClose(
		&o.testdataPrograms,
		&o.testdataMaps,
	)
}

// testdataMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataMaps struct {
}

func (m *testdataMaps) Close() error {
	return _TestdataClose()
}

// testdataVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataVariables struct {
}

// testdataPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataPrograms struct {
	Test *ebpf.Program `ebpf:"test"`
}

func (p *testdataPrograms) Close() error {
	return _TestdataClose(
		p.Test,
	)
}

func _TestdataClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed testdata_bpfeb.o
var _TestdataBytes []byte
