// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package internal

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type testdataCounters struct {
	_   structs.HostLayout
	Foo uint64
	Bar struct {
		_        structs.HostLayout
		Martians uint64
	}
}

type testdataStatsByFunction struct {
	_        structs.HostLayout
	Upstream struct {
		_  structs.HostLayout
		Rx struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
		Tx struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
		Drop struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
		Pass struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
	}
	Downstream struct {
		_  structs.HostLayout
		Rx struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
		Tx struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
		Drop struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
		Pass struct {
			_     structs.HostLayout
			Bytes uint64
			Pkt   uint64
		}
	}
}

type testdataToplevel struct {
	_      structs.HostLayout
	Bar    uint64
	Nested struct {
		_     structs.HostLayout
		Foo   uint64
		Dummy uint64
	}
}

type testdataToplevelCounterVec struct {
	_     structs.HostLayout
	Stats struct {
		_      structs.HostLayout
		Bar    uint64
		Nested struct {
			_     structs.HostLayout
			Foo   uint64
			Dummy uint64
		}
	}
}

type testdataToplevelTagedFields struct {
	_          structs.HostLayout
	Foo        uint64
	Bar        uint64
	CounterVec struct {
		_     structs.HostLayout
		Foo   uint64
		Dummy uint64
	}
	OverlappingTags struct {
		_      structs.HostLayout
		Bar    uint64
		Nested struct {
			_     structs.HostLayout
			Foo   uint64
			Dummy uint64
		}
	}
	Variations struct {
		_        structs.HostLayout
		Upstream struct {
			_  structs.HostLayout
			Rx struct {
				_     structs.HostLayout
				Bytes uint64
				Pkt   uint64
			}
			Tx struct {
				_     structs.HostLayout
				Bytes uint64
				Pkt   uint64
			}
		}
		Downstream struct {
			_  structs.HostLayout
			Rx struct {
				_     structs.HostLayout
				Bytes uint64
				Pkt   uint64
			}
			Tx struct {
				_     structs.HostLayout
				Bytes uint64
				Pkt   uint64
			}
		}
	}
	SingleLabel uint64
}

// loadTestdata returns the embedded CollectionSpec for testdata.
func loadTestdata() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TestdataBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load testdata: %w", err)
	}

	return spec, err
}

// loadTestdataObjects loads testdata and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*testdataObjects
//	*testdataPrograms
//	*testdataMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTestdataObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTestdata()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// testdataSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataSpecs struct {
	testdataProgramSpecs
	testdataMapSpecs
	testdataVariableSpecs
}

// testdataProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataProgramSpecs struct {
	PokeCounters *ebpf.ProgramSpec `ebpf:"poke_counters"`
}

// testdataMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataMapSpecs struct {
	CountersMap         *ebpf.MapSpec `ebpf:"counters_map"`
	StatsByFunction     *ebpf.MapSpec `ebpf:"stats_by_function"`
	Toplevel            *ebpf.MapSpec `ebpf:"toplevel"`
	ToplevelCounterVec  *ebpf.MapSpec `ebpf:"toplevel_counter_vec"`
	ToplevelTagedFields *ebpf.MapSpec `ebpf:"toplevel_taged_fields"`
}

// testdataVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type testdataVariableSpecs struct {
}

// testdataObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataObjects struct {
	testdataPrograms
	testdataMaps
	testdataVariables
}

func (o *testdataObjects) Close() error {
	return _TestdataClose(
		&o.testdataPrograms,
		&o.testdataMaps,
	)
}

// testdataMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataMaps struct {
	CountersMap         *ebpf.Map `ebpf:"counters_map"`
	StatsByFunction     *ebpf.Map `ebpf:"stats_by_function"`
	Toplevel            *ebpf.Map `ebpf:"toplevel"`
	ToplevelCounterVec  *ebpf.Map `ebpf:"toplevel_counter_vec"`
	ToplevelTagedFields *ebpf.Map `ebpf:"toplevel_taged_fields"`
}

func (m *testdataMaps) Close() error {
	return _TestdataClose(
		m.CountersMap,
		m.StatsByFunction,
		m.Toplevel,
		m.ToplevelCounterVec,
		m.ToplevelTagedFields,
	)
}

// testdataVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataVariables struct {
}

// testdataPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTestdataObjects or ebpf.CollectionSpec.LoadAndAssign.
type testdataPrograms struct {
	PokeCounters *ebpf.Program `ebpf:"poke_counters"`
}

func (p *testdataPrograms) Close() error {
	return _TestdataClose(
		p.PokeCounters,
	)
}

func _TestdataClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed testdata_bpfel.o
var _TestdataBytes []byte
