// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpftest

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadMk returns the embedded CollectionSpec for mk.
func loadMk() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mk: %w", err)
	}

	return spec, err
}

// loadMkObjects loads mk and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*mkObjects
//	*mkPrograms
//	*mkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMk()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// mkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mkSpecs struct {
	mkProgramSpecs
	mkMapSpecs
	mkVariableSpecs
}

// mkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mkProgramSpecs struct {
	Test *ebpf.ProgramSpec `ebpf:"test"`
}

// mkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mkMapSpecs struct {
}

// mkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type mkVariableSpecs struct {
}

// mkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMkObjects or ebpf.CollectionSpec.LoadAndAssign.
type mkObjects struct {
	mkPrograms
	mkMaps
	mkVariables
}

func (o *mkObjects) Close() error {
	return _MkClose(
		&o.mkPrograms,
		&o.mkMaps,
	)
}

// mkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMkObjects or ebpf.CollectionSpec.LoadAndAssign.
type mkMaps struct {
}

func (m *mkMaps) Close() error {
	return _MkClose()
}

// mkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMkObjects or ebpf.CollectionSpec.LoadAndAssign.
type mkVariables struct {
}

// mkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMkObjects or ebpf.CollectionSpec.LoadAndAssign.
type mkPrograms struct {
	Test *ebpf.Program `ebpf:"test"`
}

func (p *mkPrograms) Close() error {
	return _MkClose(
		p.Test,
	)
}

func _MkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mk_bpfeb_test.o
var _MkBytes []byte
